## YAML Template.
---
server:
  port: 9090
application:
  version: 1.0
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        use_sql_comments: false
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/tools-rental?useSSL=false&characterEncoding=utf-8&useUnicode=true&allowPublicKeyRetrieval=True
    username: root
    password: 8228023mts
platform:
  # system email settings
  systemEmailContactName: Platform support
  systemEmailContactEmail: starshistrelok@gmail.com
  # super admin registration info
  superAdminEmail: starshistrelok@gmail.com
  superAdminFirstName: Alex
  superAdminLastName: Omeluaniuk
  superAdminPassword: 8228023mts
  # domain settings
  serverDomain: http://localhost:3000
  # mailjet settings
  mailjetApiKey: 492d0272c772703cf12e9557857b9947
  mailjetSecretKey: d1808011418953c5f357a2d6a5886fee
  #navigation
  navigation:
    login: /login
    logout: /logout
    loginPage: /welcome
    protectedRest: /api/agrolavka/protected
    publicRest: /api/agrolavka/public
    registrationVerification: /verification
    views: /platform
